name: telemarketing
services:
  streamlit:
    build: docker/streamlit
    image: satriahelmy/telemarketing:streamlit
    container_name: streamlit_frontend
    depends_on:
      - api
    ports:
      - 8501:8501
    volumes:
      - ./:/home/
  api:
    build: docker/api
    image: satriahelmy/telemarketing:api
    container_name: api_backend
    ports:
      - 8080:8080
    volumes:
      - ./:/home/